### PR TITLE
Add LastLogin timestamp to LoginReply

### PR DESCRIPTION
**Pull request by bbengfort**
### Scope of changes

Adds last login to login reply so that the frontend can detect if a user has previously logged in or not. Authenticate adds the "last used" timestamp of the api key and refresh uses the issued at timestamp of the claims to prevent database lookups. Strings are RFC3339 nano timestamps.

Fixes SC-13546

### Type of change

- [x] new feature
- [ ] bug fix
- [ ] documentation
- [ ] testing
- [ ] technical debt
- [ ] other (describe)

### Acceptance criteria

Should be a quick review to see if everything makes sense. 

### Author checklist

- [x] I have manually tested the change and/or added automation in the form of unit tests or integration tests
- [ ]  I have updated the dependencies list
- [ ]  I have recompiled and included new protocol buffers to reflect changes I made
- [ ]  I have added new test fixtures as needed to support added tests
- [x]  Check this box if a reviewer can merge this pull request after approval (leave it unchecked if you want to do it yourself)
- [x]  I have moved the associated Shortcut story to "Ready for Review"

### Reviewer(s) checklist

- [ ] Any new user-facing content that has been added for this PR has been QA'ed to ensure correct grammar, spelling, and understandability.
- [ ] Are there any TODOs in this PR that should be turned into stories?

### CODE REVIEW

**Review by pdeziel — APPROVED** [review]
Looks good, do we need a companion story to update tenant?

**Comment by bbengfort** [comment]
> Looks good, do we need a companion story to update tenant?

Good point, I'll do that in this PR - thank you!

**Comment by bbengfort** [comment]
@pdeziel I updated the Tenant API side - would you mind doing a quick re-review?

**Review by pdeziel — APPROVED** [review]
Looks good, thanks for making the updates.

**Pull request merged**
