### PR TITLE
Step by step quickstart

### PR DESCRIPTION
**Pull request by pdeziel**
### Scope of changes

This adds a contribution to the docs by @Mikerniker to help clarify how to create a project, topic, and API keys using the Ensign dashboard.

### Type of change

- [ ] new feature
- [ ] bug fix
- [x] documentation
- [ ] testing
- [ ] technical debt
- [ ] other (describe)

### Acceptance criteria

[Copy acceptance criteria checklist from story for reviewer, or add a brief acceptance criteria here]

[Front-End: add screenshots/videos of changes made]

### Definition of Done

- [ ] I have manually tested the change running it locally (having rebuilt all containers) or via unit tests 
- [ ] I have added unit and/or integration tests that cover my changes
- [ ] I have added new test fixtures as needed to support added tests
- [ ] I have updated the dependencies list if necessary (including updating yarn.lock and/or go.sum)
- [ ] I have recompiled and included new protocol buffers to reflect changes I made if necessary
- [ ] Check this box if a reviewer can merge this pull request after approval (leave it unchecked if you want to do it yourself)
- [ ] I have notified the reviewer via Shortcut or Slack that this is ready for review
- [ ] Front-end: Checked sm, md, lg screen resolutions for effective responsiveness
- [ ] Backend-end: Documented service configuration changes or created related devops stories

### Reviewer(s) checklist

- [ ] Front-end: I've reviewed the Figma design and confirmed that changes match the spec.
- [ ] Any new user-facing content that has been added for this PR has been QA'ed to ensure correct grammar, spelling, and understandability.
- [ ] Are there any TODOs in this PR that should be turned into stories?

### CODE REVIEW

**Comment by pdeziel** [comment]
@Mikerniker Thanks for you persistent effort in dealing with the GitHub issues, I think your contribution is great and I want it on website so I just transplanted your edits here to move things along. Can you give this a quick look over to make sure that I didn't miss anything?

**Comment by Mikerniker** [comment]
@pdeziel Yes, it looks fine.
I just saw that my GPG for [ PR#776](https://github.com/rotationalio/ensign/pull/776) still appears unverified on Github, not sure why that is (emails are the same), but will try to find what went wrong.
Thanks for your help and patience!

**Review by rebeccabilbro — APPROVED** [review]
Thank you so much @Mikerniker for your generous contribution to this project!

**Comment by Mikerniker** [comment]
Thank you too @rebeccabilbro !

**Pull request merged**
